version: "3.9"
services:
  express:
    build: .
    ports:
    - "${PORT}:${PORT}"
    env_file: .env
  postgres:
    image: postgres:alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: .env
    volumes:
    - postgres:/var/lib/postgresql/data
volumes:
  postgres:
